### ISSUE TITLE
Fonctionnalité cacher un onglet du menu

### ISSUE THREAD

**Issue by AlexisGiust** [APLEB-Polytech/ptitbiomed_projet#106]

**Comment by baudu69** [comment]
On peut pas juste créer l'article et le mettre dans la navbar quand on veut ?

**Comment by AlexisGiust** [comment]
Si, mais la je parle de l'onglet partenaire par exemple.
On peut préparer les sous menu mais comme le menu parent est caché alors les sous-menus aussi.

**Comment by baudu69** [comment]
Un attribut hidden du coup sur l'objet en base ?

**Comment by AlexisGiust** [comment]
Oui je pensais à ça
