### ISSUE TITLE
La compilation du back lance la compilation du front

### ISSUE THREAD

**Issue by AlexisGiust** [APLEB-Polytech/ptitbiomed_projet#108]

**Comment by baudu69** [comment]
Pas de solutions durable pour le moment a part commenter la ligne : 
https://github.com/APLEB-Polytech/ptitbiomed_projet/blob/440bf5c13395359f8b1c7cb0e047018303e9ff9f/ptitbiomed-api/build.gradle#L16
Il faut absolument qu'elle soit de nouveau decomente avant de push
